'use client'
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/WNF43uBQMgc
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CarouselItem, CarouselContent, Carousel } from "@/components/ui/carousel"
import Image from "next/image"
import Autoplay from 'embla-carousel-autoplay';

type Images = {
  alt: string;
  src: string;
}

export function HeaderCarousel({title, desc, Images} : {title: string, desc: string, Images: Images[]}) {
  return (
    <section className="relative h-[73vh] w-full overflow-hidden">
      <Carousel  className="absolute inset-0 h-full w-full" plugins={[
      Autoplay({
        delay: 2000,
      }),
    ]}
      >
        <CarouselContent className="opacity-70 bg-black">
          {Images.map((image, index) => (
          <CarouselItem key={index}>
             <Image
               alt={image.alt}
               className="h-[720px] w-full object-cover"
               height="720"
               src={image.src}
               style={{
                 aspectRatio: "1280/720",
                 objectFit: "cover",
               }}
               width="1280"
            />
          </CarouselItem>
        ))}
        </CarouselContent>
      </Carousel>
      <div className="relative z-0 flex h-full w-full items-center justify-center mt-32">
      <div className="p-content">
            <div className="p-title">
                <p className="t-text">{title}</p>
            </div>
            <div className="p-desc">
                <p className="d-text">{desc}</p>
            </div>
        </div>
      </div>
    </section>
  )
}
