import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
import Image from "next/legacy/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header />
        {children}
        <a href="https://api.whatsapp.com/send?phone=5517981654034" target="_blank" className="custom-link">
          <Image src="/img/icoWhatsapp.png" alt="WhatsApp" width={40} height={40} />
        </a>
        <Footer />
        </body>
    </html>
  );
}
